name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  e2e-status:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Tests payload - Dispatch response to received run_e2e
        if: github.event.action == 'run_e2e'
        steps:
          - uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node }}
          - uses: actions/checkout@v1
          - name: Run TestCafe Tests
            uses: DevExpress/testcafe-action@latest
          - name: Tests Passed
            run: |
              curl -X POST https://api.github.com/repos/lu97chi/netlifyForceError/dispatches \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              -u ${{ secrets.ACCESS_TOKEN }} \
              --data '{"event_type": "test_status", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", status: 'Passed' }}'


          